### ISSUE TITLE
Ignore messages from bots

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/sweetiebot#51]
If a user has the Bot tag, it must 1) be an official public bot and 2) must have been explicitly invited to the server by the server owner. Because of this there's no reason for sweetiebot to ever track spam from them. In fact, Sweetie should ignore all messages from all bots as no bot should be able to trigger her commands in the first place.

**Comment by Kanzuke117** [comment]
Heya, we have two private bots acting as relays for in-game chat, which means at the moment, with bot messages treated like any other, people can use Sweetie's public commands directly in-game. It does  make sense to exclude them from spam-detection (I don't wanna know what happens when Sweetie tries to silence a webhook), but I'd appreciate a config option to toggle ignoring all bot messages.

**Comment by blackhole12** [comment]
@Kanzuke117 I intend for sweetie to exclude bots from spam-detection at the very least, but are you asking for an option for sweetiebot to ignore all _commands_ issued from a bot?

**Comment by Kanzuke117** [comment]
Nono, I'm asking that if you decide to go ahead and made Sweetie ignore all commands from bots that there be a config option to _re-enable_ checking bot messages; to preserve the current functionality.
