### ISSUE TITLE
!fight does not escape characters

### ISSUE THREAD

**Issue by Aquaeyes** [blackhole12/sweetiebot#70]
When using the ` character to create a code block after !fight, it is possible that Sweetie Bot doesn't escape the character, causing the code blocks to be broken in her reply message. This is purely visual, and everything else works perfectly.

**Comment by blackhole12** [comment]
This is impossible to fix, because you cannot escape characters inside code blocks.
![image](https://user-images.githubusercontent.com/3387013/34506680-d63fb626-efe3-11e7-9f52-5580df542aa4.png)
The dangling ` is impossible to get rid of and inherently makes it impossible to display the entire string needed to remove the item so long as they are displayed in a code block. The only way around this would be to remove the code block entirely, but if your goal is to ensure you can always remove something from the bucket, this won't work very well either because people can just insert emoji once they're no longer in a codeblock jail to mess it up anyway.
